#!/usr/bin/python

import os
import os.path
import shutil

# Check if EndNote Cite While You Write is already installed
endnote_bundle_2008 = os.path.exists("/Applications/Microsoft Office 2008/Office/Startup/Word/EndNote CWYW Word 2008.bundle")
endnote_bundle_2011 = os.path.exists("/Applications/Microsoft Office 2011/Office/Startup/Word/EndNote CWYW Word 2011.bundle")

def check_endnote_2008():
	# If the CWYW bundle is installed for Office 2008, then remove it
	if endnote_bundle_2008:
		print "EndNote bundle is installed for Office 2008"
		shutil.rmtree("/Applications/Microsoft Office 2008/Office/Startup/Word/EndNote CWYW Word 2008.bundle")
		print "Removed the CWYW bundle form 2011"
	else:
		print "EndNote bundle is not installed for Office 2008"
		print "Checking Office 2011 now"

def check_endnote_2011():
	# If the CWYW bundle is installed for Office 2011, then remove it
	if endnote_bundle_2011:
		print "EndNote bundle is installed for Office 2011"
		shutil.rmtree("/Applications/Microsoft Office 2011/Office/Startup/Word/EndNote CWYW Word 2011.bundle")
		print "Removed the CWYW bundle form 2011"
	else:
		print "EndNote bundle is not installed for Office 2011"
		print "Proceeding with installation"

def main():
	check_endnote_2008()
	check_endnote_2011()

main()